/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinRouteImport } from './routes/skin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as HairRouteImport } from './routes/hair'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BridalMakeupRouteImport } from './routes/bridal-makeup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SkinRoute = SkinRouteImport.update({
  id: '/skin',
  path: '/skin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HairRoute = HairRouteImport.update({
  id: '/hair',
  path: '/hair',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalMakeupRoute = BridalMakeupRouteImport.update({
  id: '/bridal-makeup',
  path: '/bridal-makeup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-makeup': typeof BridalMakeupRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hair': typeof HairRoute
  '/services': typeof ServicesRoute
  '/skin': typeof SkinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-makeup': typeof BridalMakeupRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hair': typeof HairRoute
  '/services': typeof ServicesRoute
  '/skin': typeof SkinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal-makeup': typeof BridalMakeupRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hair': typeof HairRoute
  '/services': typeof ServicesRoute
  '/skin': typeof SkinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bridal-makeup'
    | '/contact'
    | '/gallery'
    | '/hair'
    | '/services'
    | '/skin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bridal-makeup'
    | '/contact'
    | '/gallery'
    | '/hair'
    | '/services'
    | '/skin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bridal-makeup'
    | '/contact'
    | '/gallery'
    | '/hair'
    | '/services'
    | '/skin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BridalMakeupRoute: typeof BridalMakeupRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HairRoute: typeof HairRoute
  ServicesRoute: typeof ServicesRoute
  SkinRoute: typeof SkinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skin': {
      id: '/skin'
      path: '/skin'
      fullPath: '/skin'
      preLoaderRoute: typeof SkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair': {
      id: '/hair'
      path: '/hair'
      fullPath: '/hair'
      preLoaderRoute: typeof HairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal-makeup': {
      id: '/bridal-makeup'
      path: '/bridal-makeup'
      fullPath: '/bridal-makeup'
      preLoaderRoute: typeof BridalMakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BridalMakeupRoute: BridalMakeupRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HairRoute: HairRoute,
  ServicesRoute: ServicesRoute,
  SkinRoute: SkinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
